INSERT INTO DEPARTMENT (ID, NAME) VALUES (1, 'HR');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (2, 'Engineering');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (3, 'Marketing');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (4, 'Sales');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (5, 'Finance');
