CREATE TABLE TESTDB.PUBLIC.DEPARTMENT (
    ID   BIGINT       NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (id)
);

CREATE TABLE TESTDB.PUBLIC.POSITION (
    ID    BIGINT       NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CONSTRAINT pk_position PRIMARY KEY (id)
);

CREATE TABLE TESTDB.PUBLIC.MEMBER (
    ID         BIGINT AUTO_INCREMENT NOT NULL,
    NAME       VARCHAR(255)          NOT NULL,
    AGE        VARCHAR(255)          NOT NULL,
    EMAIL      VARCHAR(255)          NOT NULL,
    PHONE      VARCHAR(255)          NOT NULL,
    DEPARTMENT VARCHAR(255)          NOT NULL,
    POSITION   VARCHAR(255)          NOT NULL,
    CONSTRAINT pk_member PRIMARY KEY (id)
);

CREATE TABLE TESTDB.PUBLIC.TG_GRID (
    SN BIGINT PRIMARY KEY,
    GRID VARCHAR(100) NOT NULL,
    NAME VARCHAR(100),
    USE_YN CHAR(1) NOT NULL
);

CREATE TABLE TESTDB.PUBLIC.TG_GRID_ATTR (
    SN BIGINT PRIMARY KEY,
    GRID_SN BIGINT NOT NULL,
    ATTR VARCHAR(100) NOT NULL,
    USE_YN CHAR(1) NOT NULL,
    CONSTRAINT FK_GRID_ATTR_GRID FOREIGN KEY (GRID_SN) REFERENCES TG_GRID(SN),
    CONSTRAINT UK_GRID_ATTR UNIQUE (SN, ATTR)
);

CREATE TABLE TESTDB.PUBLIC.TG_GRID_ATTR_ITEM (
    SN BIGINT PRIMARY KEY,
    ATTR_SN BIGINT NOT NULL,
    ATTR_ITEM VARCHAR(100) NOT NULL,
    ATTR_VALUE VARCHAR(255),
    USE_YN CHAR(1) NOT NULL,
    CONSTRAINT FK_GRID_ATTR_ITEM FOREIGN KEY (ATTR_SN) REFERENCES TG_GRID_ATTR(SN)
);

CREATE TABLE TESTDB.PUBLIC.TG_DATA (
    SN BIGINT PRIMARY KEY,
    DATA VARCHAR(100) NOT NULL,
    NAME VARCHAR(100),
    USE_YN CHAR(1) NOT NULL
);

CREATE TABLE TESTDB.PUBLIC.TG_DATA_ATTR (
    SN BIGINT PRIMARY KEY,
    DATA_SN BIGINT NOT NULL,
    ATTR VARCHAR(100) NOT NULL,
    USE_YN CHAR(1) NOT NULL,
    CONSTRAINT FK_DATA_ATTR FOREIGN KEY (DATA_SN) REFERENCES TG_DATA(SN)
);

CREATE TABLE TESTDB.PUBLIC.TG_DATA_ATTR_ITEM (
    SN BIGINT PRIMARY KEY,
    ATTR_SN BIGINT NOT NULL,
    ATTR_ROW INT NOT NULL,
    ATTR_ITEM VARCHAR(100) NOT NULL,
    ATTR_VALUE VARCHAR(255),
    USE_YN CHAR(1) NOT NULL,
    CONSTRAINT FK_DATA_ATTR_ITEM FOREIGN KEY (ATTR_SN) REFERENCES TG_DATA_ATTR(SN)
);
