INSERT INTO POSITION (ID, TITLE) VALUES (1, 'Intern');
INSERT INTO POSITION (ID, TITLE) VALUES (2, 'Staff');
INSERT INTO POSITION (ID, TITLE) VALUES (3, 'Senior Staff');
INSERT INTO POSITION (ID, TITLE) VALUES (4, 'Manager');
INSERT INTO POSITION (ID, TITLE) VALUES (5, 'Director');

